# Generated by Django 4.1.7 on 2023-09-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0004_personaldetailsmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetailsmodel',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'SINGLE'), ('Married', 'MARRIED'), ('Widowed', 'WIDOWED')], max_length=50),
        ),
    ]
