# Generated by Django 4.1.7 on 2023-09-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0006_remove_languagemodel_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetailsmodel',
            name='language',
        ),
        migrations.AddField(
            model_name='languagemodel',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CV.personaldetailsmodel'),
            preserve_default=False,
        ),
    ]
