# Generated by Django 4.1.7 on 2023-09-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0011_educationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='CV.personaldetailsmodel'),
            preserve_default=False,
        ),
    ]
