# Generated by Django 4.1.7 on 2023-09-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0012_educationmodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='clg_address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
