# Generated by Django 4.1.7 on 2023-09-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0015_alter_educationmodel_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='passing_date',
            field=models.CharField(max_length=50),
        ),
    ]
