# Generated by Django 4.1.7 on 2023-09-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0016_alter_educationmodel_passing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='percentage',
            field=models.FloatField(max_length=50),
        ),
    ]
