# Generated by Django 4.1.7 on 2023-09-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0018_skill_programinglanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programinglanguage',
            name='skill',
        ),
        migrations.AddField(
            model_name='programinglanguage',
            name='lang_info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='programing_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CV.programinglanguage'),
            preserve_default=False,
        ),
    ]
