# Generated by Django 4.1.7 on 2023-09-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0019_remove_programinglanguage_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='programing_language',
        ),
        migrations.AddField(
            model_name='programinglanguage',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CV.skill'),
            preserve_default=False,
        ),
    ]
