# Generated by Django 4.1.7 on 2023-09-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0020_remove_skill_programing_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programinglanguage',
            old_name='lang_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='programinglanguage',
            old_name='prog_language',
            new_name='name',
        ),
        migrations.CreateModel(
            name='FrameworksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.skill')),
            ],
        ),
    ]
