# Generated by Django 4.1.7 on 2023-09-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0021_rename_lang_info_programinglanguage_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptingLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.skill')),
            ],
        ),
    ]
