# Generated by Django 4.1.7 on 2023-09-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0022_scriptinglanguages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CV.personaldetailsmodel'),
        ),
    ]
