# Generated by Django 4.1.7 on 2023-09-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0028_workexperience_workduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workduration',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workduration',
            name='startdate',
            field=models.DateField(),
        ),
    ]
