# Generated by Django 4.1.7 on 2023-09-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0030_workexperience_company_workexperience_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='source',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
