# Generated by Django 4.1.7 on 2023-09-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0031_workexperience_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjctsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typo', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('clientname', models.CharField(blank=True, max_length=100)),
                ('technologies', models.CharField(max_length=200)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('info', models.TextField()),
                ('source', models.URLField(blank=True)),
            ],
        ),
    ]
