# Generated by Django 4.1.7 on 2023-09-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0032_projctsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projctsmodel',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
