# Generated by Django 4.1.7 on 2023-09-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0033_projctsmodel_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='projctsmodel',
            name='dura',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
