# Generated by Django 4.1.7 on 2023-09-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0034_projctsmodel_dura'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomplishmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('files', models.ImageField(upload_to='')),
                ('sorce', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sorce', models.URLField()),
            ],
        ),
    ]
