# Generated by Django 4.1.7 on 2023-09-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0035_accomplishmentmodel_sociallink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomplishmentmodel',
            old_name='sorce',
            new_name='source',
        ),
    ]
