# Generated by Django 5.1.5 on 2025-02-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0039_alter_accomplishmentmodel_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishmentmodel',
            name='files',
            field=models.ImageField(upload_to=''),
        ),
    ]
